### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by BoxFishLab** [csbhr/FFHQ-UV#1]

**Comment by BoxFishLab** [comment]
when open the source code?

**Comment by csbhr** [comment]
The FFHQ-UV dataset is now available, and a new version dataset (FFHQ-UV-Interpolation) will be available in a few days, which is based on latent space interpolation and with compromised diversity but higher quality and larger scale (100,000 UV-maps).

But, there is still some code organization work to be done before the source code can be released, thanks for attention.

**Comment by miaoYuanyuan** [comment]
what is the extract code ?

**Comment by ujjawalcse** [comment]
Eagerly waiting!!

**Comment by zhanghongyong123456** [comment]
> Eagerly waiting!!

Same too

**Comment by csbhr** [comment]
The **FFHQ-UV-Interpolate** dataset is now available. Welcome to follow and discuss.

**Comment by ohjarwa** [comment]
> The **FFHQ-UV-Interpolate** dataset is now available. Welcome to follow and discuss.

Hi! Thanks for your great work.
Will you share the code of 'face uv extraction' or face reconstruction?
Thanks.

**Comment by csbhr** [comment]
Thanks for your attention. We will release the source code around the end of December.

**Comment by ohjarwa** [comment]
> Thanks for your attention. We will release the source code around the end of December.
OK! Look forward to. Thank you.

**Comment by ohjarwa** [comment]
> Thanks for your attention. We will release the source code around the end of December.

By the way, I have two more questions: 1) how to do the 'unwrap' process 2) Once I get the uvmap, how to wrap the map to the non-texture mesh. 

Thank you.

**Comment by ujjawalcse** [comment]
Hi @ohjarwa @csbhr , 
I think we will have to unwrap custom mesh to UVmap in a 3D tool manually in such a way that can be fit to 
the uv-texture of this repository.
Me too want to use the uv-texture of this repository on other head mesh.
Let us know any automated way to get it.
