### ISSUE TITLE
关于render的疑问

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [csbhr/FFHQ-UV#13]
你好，关于render我有一个疑问，
![image](https://user-images.githubusercontent.com/30692249/220529748-6d21a49f-de66-4015-8ac4-997fc4c1343d.png)
为什么这里对于UV texture的渲染选择的点映射呢，而不是直接使用dr.texture进行uv渲染，后者会有更好的渲染效果，但是我不确定对于收敛的影响，请问有做过相关的收敛对比吗

**Comment by happyday521** [comment]
我也有相同的疑问，请问解决了吗

**Comment by happyday521** [comment]
感谢解答！

**Comment by ZHANG-SHI-CHANG** [comment]
感谢回复！
这种写法会更容易收敛不

**Comment by csbhr** [comment]
暂时没有做收敛速度的比较，但从直觉上，应该是相似的。如果感兴趣，可以尝试对比一下看看。
