### ISSUE TITLE
About front face in edit phase

### ISSUE THREAD

**Issue by MontaEllis** [csbhr/FFHQ-UV#15]
Thanks for your great work! But I wonder why the '01223_front.png' in your repo is totally front. I didn't found align code in 'run_styleflow_edit.py'. It seems like you load the inversed code to generate front face directly.

**Comment by csbhr** [comment]
On Line240-Line241 of "run_styleflow_edit.py", we set the target value of head pose (e.g., yaw, pitch) to zero, producing a front face.

https://github.com/csbhr/FFHQ-UV/blob/37cb663d823067e644677f9ae89c64759126791c/DataSet_Step3_Editing/run_styleflow_editing.py#L237-L244
