### ISSUE TITLE
About incorrpondence hair in uv

### ISSUE THREAD

**Issue by MontaEllis** [csbhr/FFHQ-UV#17]
I run uv_unwarp code and found the hair is incorrpondent with your released one.

![](https://ellis.oss-cn-beijing.aliyuncs.com/img20230301140510.png)

**Comment by csbhr** [comment]
At the final step, we cover hair region with template UV map. Please check the codes of this part.

https://github.com/csbhr/FFHQ-UV/blob/37cb663d823067e644677f9ae89c64759126791c/DataSet_Step4_UV_Texture/tex/tex_func.py#L264-L271
