### ISSUE TITLE
关于生成uv纹理数据集的疑问

### ISSUE THREAD

**Issue by Joel18241096** [csbhr/FFHQ-UV#18]
作者您好，首先感谢您做出的这份令人惊叹的工作。如果我想要使用您开源的代码，生成一套基于BFM系数（您论文中提到使用的是HIFI3D++系数）的纹理uvmap数据集，请问是可行的吗？具体地我需要在您这里面更改多少地方呢？多谢！

**Comment by csbhr** [comment]
你好，如果想生成一套 BFM 系数的 UVmap 数据集，需要重新跑一遍 step4（DataSet_Step4_UV_Texture）的扒皮代码，其中需要：
1. 训练一个基于 BFM 系数的 Deep3D 模型来预测 normalized multi-view faces 的 shape；
2. 制作 BFM 拓扑相关的 [[topo assets]](https://github.com/csbhr/FFHQ-UV/blob/main/README_ckp_topo.md#the-topology-assets-used-in-ffhq-uv-project)，其中包括：在扒皮过程中需要使用的mask（*_mask.png）、BFM model（hifi3dpp_model_info.mat）、mesh上的68个3D landmark坐标（similarity_Lm3D_all.mat）、栅格化的“UV <--> mesh”的坐标关系（unwrap_1024_info.mat）。
