### ISSUE TITLE
Do you have any plans to release the original face images dataset

### ISSUE THREAD

**Issue by xingpeima** [csbhr/FFHQ-UV#2]

**Comment by csbhr** [comment]
The file size of the face image dataset is too large to be uploaded.

Instead, we have released the latent codes of the multi-view normalized face images which are used for extracting texture UV-maps. Please refer to [README](https://github.com/csbhr/FFHQ-UV#the-latent-codes-of-the-normalized-face-images).
You can generate face images by [StyleGAN2](https://github.com/NVlabs/stylegan2) using the official pre-trained [checkpoint](http://d36zk2xti64re0.cloudfront.net/stylegan2/networks/stylegan2-ffhq-config-f.pkl).

Welcome to follow and discuss.

**Comment by csbhr** [comment]
The script for generating face images from latent codes is available.
Please refer to [README](https://github.com/csbhr/FFHQ-UV#the-latent-codes-and-attributes-of-the-normalized-face-images).
