### ISSUE TITLE
关于投影矩阵和坐标系变换的问题

### ISSUE THREAD

**Issue by happyday521** [csbhr/FFHQ-UV#21]
您好，感谢您分享的工作！我刚接触该方向，有几个关于代码中投影矩阵以及坐标系变换的基础问题向您请教：

1、在render_nvdiffrast.py文件中的line19-20，为什么需要将ndc_projection得到的投影矩阵跟torch.diag(torch.tensor([1., -1, -1, 1]))的对角阵相乘？这一步的物理意义是什么？
![image](https://user-images.githubusercontent.com/35884085/224984531-4efcd27b-1a93-41cc-beed-c4923083e134.png)

2、在render_nvdiffrast.py文件中的line53，为什么需要将vertex的y坐标取负号？这一步的物理意义是什么？
![image](https://user-images.githubusercontent.com/35884085/224984862-d87fe526-b90a-49ef-8d58-689e991d4a72.png)

期待您的回复，谢谢！

**Comment by csbhr** [comment]
你好，这部分的相机内参，我们与 [[Deep3D]](https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/master/util/nvdiffrast.py) 保持一致，采用了相同的设置。

对于这两处代码，都是将坐标取负号，应该是不同工具间坐标系方向设置相反的原因，在转换坐标系时需要进行转换。
