### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by kelu007** [csbhr/FFHQ-UV#23]
I've followed README to constuct the required environment and run the run_rgb_fitting.sh. But I got the following errors, could you please help me solve it?
<img width="791" alt="image" src="https://user-images.githubusercontent.com/48619529/230383251-93572f46-dacc-4fa3-9068-9c74defc2ee6.png">

**Comment by csbhr** [comment]
It seems that there is no face detected.
