### ISSUE TITLE
关于眼球安装的问题

### ISSUE THREAD

**Issue by kk5pengke** [csbhr/FFHQ-UV#24]
您好，感谢您分享的工作！我想问一下关于眼球安装的问题。我现在遇到一个问题，run_mesh_add_eyeball中先按照包络关键点进行刚性对齐，再按照眼眶进行位置微调的方法很棒。但我发现hifi3d生成结果中不同的人会存在左右眼球包络并不对称的情况，进而导致左右眼安装不对称的问题，不知道您是否遇到过。

**Comment by csbhr** [comment]
我没有太注意到这个问题，这似乎是因为拟合的head mesh眼眶不对称导致的？最好能根据具体的样本分析一下。

**Comment by pyh007** [comment]
请问下眼球那块的模型和贴图是固定的还是每个人生成的不同
