### ISSUE TITLE
期待一个colab版本

### ISSUE THREAD

**Issue by skyeKing** [csbhr/FFHQ-UV#25]
如题

**Comment by slime898** [comment]
Unfortunately, colab removed support for Tensorflow 1.x, so it's impossible.

**Comment by yumkim381** [comment]
Running this code on colab is still possible! works for me

**Comment by YiChenCityU** [comment]
> Running this code on colab is possible! works for me

Do you have an example to run it on colab? Thanks very much.

**Comment by yumikim381** [comment]
I think this is the code i used back then. Hope this helps!
# -*- coding: utf-8 -*-
"""FFHQ-UV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wq46NpggjpGKLbEQ6bAGZqY3Xkx_3mxa

#Git clone this repository and their script.
"""

from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd gdrive/MyDrive
# %cd FFHQ-UV

!echo $PYTHONPATH

# Commented out IPython magic to ensure Python compatibility.
# %env PYTHONPATH=

!echo $PYTHONPATH

! wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.1.0-1-Linux-x86_64.sh
! chmod +x Miniconda3-py39_23.1.0-1-Linux-x86_64.sh
! bash ./Miniconda3-py39_23.1.0-1-Linux-x86_64.sh -b -f -p /usr/local/

#apparently updating conda is neccessary # run as well
!conda install --channel defaults conda python=3.9 --yes
!conda update --channel defaults --all --yes

!chmod +x install_conda.sh

!conda init bash
!exec bash

conda create -n ffhq python=3.7 -y
conda activate ffhq
pip install torch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2
pip install dlib
pip install tensorboard
pip install tensorflow-gpu==1.15.0
pip install --upgrade azure-cognitiveservices-vision-face
pip install tqdm scikit-image opencv-python pillow imageio matplotlib mxnet Ninja google-auth google-auth-oauthlib click requests pyspng imageio-ffmpeg==0.4.3 scikit-learn torchdiffeq==0.0.1 flask kornia==0.2.0 lmdb psutil dominate rtree

cd thirdparty
conda install -c bottler nvidiacub
#this below needs to work OW try again
pip install -e iopath
pip install -e fvcore
pip install -e nvdiffrast
cd ..
chmod +x run_rgb_fitting_cropface630resize1024.sh
./run_rgb_fitting_cropface630resize1024.sh

**Comment by prthameshhh** [comment]
> I think this is the code i used back then. Hope this helps!
> 
> from google.colab import drive drive.mount('/content/gdrive')
> 
> !echo $PYTHONPATH
> 
> !echo $PYTHONPATH
> 
> ! wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.1.0-1-Linux-x86_64.sh ! chmod +x Miniconda3-py39_23.1.0-1-Linux-x86_64.sh ! bash ./Miniconda3-py39_23.1.0-1-Linux-x86_64.sh -b -f -p /usr/local/
> 
> #apparently updating conda is neccessary # run as well !conda install --channel defaults conda python=3.9 --yes !conda update --channel defaults --all --yes
> 
> !chmod +x install_conda.sh
> 
> !conda init bash !exec bash
> 
> conda create -n ffhq python=3.7 -y conda activate ffhq pip install torch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 pip install dlib pip install tensorboard pip install tensorflow-gpu==1.15.0 pip install --upgrade azure-cognitiveservices-vision-face pip install tqdm scikit-image opencv-python pillow imageio matplotlib mxnet Ninja google-auth google-auth-oauthlib click requests pyspng imageio-ffmpeg==0.4.3 scikit-learn torchdiffeq==0.0.1 flask kornia==0.2.0 lmdb psutil dominate rtree
> 
> cd thirdparty conda install -c bottler nvidiacub #this below needs to work OW try again pip install -e iopath pip install -e fvcore pip install -e nvdiffrast cd .. chmod +x run_rgb_fitting_cropface630resize1024.sh ./run_rgb_fitting_cropface630resize1024.sh



can you please share a colab file that you were able to run
