### ISSUE TITLE
您好～咨询论文中提到的对比方法

### ISSUE THREAD

**Issue by Luh1124** [csbhr/FFHQ-UV#26]
您好，感谢您杰出的工作带来的灵感，想了解您在对比试验中提到了ganfit和avatarme，但是找了很久没找到开源代码，想了解是否有其他推理方式？或者您推荐类似的相关方法还有哪些？

**Comment by csbhr** [comment]
关于与ganfit和avatarme的对比，我们将数据发送给论文作者，他们帮助测试的
