### ISSUE TITLE
pytorch3d版本问题

### ISSUE THREAD

**Issue by yummyJade** [csbhr/FFHQ-UV#27]
您好，感谢您出色的工作!
我注意到该项目有部分环境要求为pytorch1.7.1+tensorflow1.5+cuda10.0，但是同时该项目又要安装pytorch3d，但是目前最新版本pytorch3d(0.7.4)支持的pytorch范围为PyTorch 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 2.0.0 or 2.0.1，请问应该使用哪一个版本的pytorch3d才能在该项目环境下正常使用呢？

**Comment by rlczddl** [comment]
0.7.1以下的版本，以上的版本不支持py37；从源码安装。

**Comment by yummyJade** [comment]
> 0.7.1及以下的版本，以上的版本不支持py37；从源码安装。

十分感谢！

**Comment by pyh007** [comment]
如何从源码安装呢
