### ISSUE TITLE
Shape meshes corresponding to the texture UV

### ISSUE THREAD

**Issue by mashrurmorshed** [csbhr/FFHQ-UV#29]
Is there a way to obtain the shape/face meshes corresponding to the ~50K texture UVs in the dataset?

If I simply take an FFHQ image and apply RGBFitting to it, the obtained texture doesn't look as highly detailed as the one in the provided dataset.

One option is to apply RGBFitting on an FFHQ image, and then simply take the output identity mesh and match it to the corresponding texture in the dataset. But this might not be entirely correct, since the dataset textures are combinations of textures from 3 different views, right?

**Comment by csbhr** [comment]
In fact, the face meshes corresponding to the ~50K UV-texture maps in the FFHQ-UV dataset can be obtained through the Stage 1 of the proposed RGB Fitting algorithm, that is, the output of the trained Deep3D (refer to "Stage 1: linear 3DMM initialization" in paper).

Specifically, you can apply the RGB Fitting code to the normalized frontal face, and then take the face mesh output from the Stage 1.
