### ISSUE TITLE
Help ! MS API Error 

### ISSUE THREAD

**Issue by NaToh5** [csbhr/FFHQ-UV#33]
When I run python run_ms_api_attr.py --proj_data_dir ../examples/dataset_examples. I got his error 
>> Error: 'Endpoint'.
>> MS API error, sleep 2 minutes and retry 1-st.
![image](https://github.com/csbhr/FFHQ-UV/assets/134680400/cdacf017-85ed-4529-b4a5-cebad640afb8)

**Comment by pyh007** [comment]
同样的错误，解决了吗

**Comment by NaToh5** [comment]
solved ? Did you solve it ?

**Comment by pyh007** [comment]
我这也刚遇到，暂时还没解决。

**Comment by NaToh5** [comment]
I think developer no longer support this repo.
