### ISSUE TITLE
Downloading dataset from OneDrive

### ISSUE THREAD

**Issue by mmkuznecov** [csbhr/FFHQ-UV#36]
Hello!

Thanks for great work! I am currently trying to download a dataset from OneDrive (can not use Baidu as far as I'm not living in China). I have tried to generate link from network using method provided [here](https://stackoverflow.com/questions/62634214/how-to-download-protected-files-from-onedrive-using-wget) to download dataset directly to my remote server. But loading always interrupts, and I get only 15-17 GBs from 180. Manual downloading is challenging too, because a little network issue ruins all loading.

You provided a script for downloading the dataset from AWS [here](https://github.com/csbhr/FFHQ-UV/issues/3) but later you deprecated it. If there is some link to it, could you, please, share it?

Could you, please, provide some script/method for automatic downloading from OneDrive or maybe you have some S3 link?

**Comment by csbhr** [comment]
Sorry, we no longer maintain AWS due to cost issues. 

For the convenience of downloading, we have divided the dataset into fragments of about 1G. 
You can consider downloading in batches one by one, without worrying about network fluctuations causing all re-downloads.
