### ISSUE TITLE
The question of 3d face reconstruction

### ISSUE THREAD

**Issue by xingpeima** [csbhr/FFHQ-UV#4]
Hi, I have already read your paper and I think the three stages reconstruction method mentioned in your paper is very great!
But I’m still a little confused in stage 2 that how to converted the parameter {Pid, Pexp, Ppose, Plight} to z？

**Comment by csbhr** [comment]
Thanks for attention. Actually, we do not converted the parameters {p_id, p_exp, p_pose, p_light} to z.
From Stage-1, we get the initial parameters {p_id, p_exp, p_pose, p_light}. In Stage-2, we just fix them and optimize z via Eq. (4), starting from a random initialization.
It is a optimization-based method, where z is randomly initialized and updated by back-propagation.
