### ISSUE TITLE
How can I train my own texgan model on custom dataset?

### ISSUE THREAD

**Issue by wangmingyang4** [csbhr/FFHQ-UV#43]
Thanks your work. I want to train my own texgan model and hope to get some guidance.

**Comment by csbhr** [comment]
We use the codes from [StyleGAN2-ADA-PyTorch](https://github.com/NVlabs/stylegan2-ada-pytorch) to train a StyleGAN2, and take it as the texgan model.

**Comment by 4d5645** [comment]
Can you give instructions on exactly how you conducted the training?
