### ISSUE TITLE
latents for FFHQ subjects

### ISSUE THREAD

**Issue by ankarako** [csbhr/FFHQ-UV#47]
Hi and thank you very much for you contribution!

Although you provide extensive documentation for some things, I still cannot understand how to export 3d meshes for the FFHQ subjects.
Are there latent codes that correspond to HIFI3D 3dmm?
If I understood correctly, the `run_gen_face_from_latent.sh` script generates images and not 3D objects.

Could you help me identify what I'm missing?

(and btw the objs created with script for adding eyeballs miss the 'usemtl' line in the resulting .obj)

Thanks for your time.

**Comment by slime898** [comment]
You can use 'run_rgb_fitting.sh' to generate UV map and 3D object files.

**Comment by ankarako** [comment]
So you basically have to infer the whole FFHQ dataset. Thanks
