### ISSUE TITLE
How to create rendering video as yours? 

### ISSUE THREAD

**Issue by yumkim381** [csbhr/FFHQ-UV#53]
Hi thank you so much for publishing your excellent work!
May i ask you how you created these youtube video (https://www.youtube.com/watch?v=dXFRJODJlNY&ab_channel=HaoranBai)?
I m new to the topic, so i would really appreciate it if you could point me how to create those. 
Kind regards, 
Yumi

**Comment by mengxuyiGit** [comment]
Hi i am also interested in rendering the mesh, could you please share how you achieved this? Many thanks!
