### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by pyh007** [csbhr/FFHQ-UV#54]
请问下为什么生成的uv有些的是朝左有些图片是朝右。
![51](https://github.com/csbhr/FFHQ-UV/assets/37687691/49d5cb7f-b729-4e17-99fc-ba8b500a521c)
![52](https://github.com/csbhr/FFHQ-UV/assets/37687691/a0ace9a8-290d-484c-a60b-e6b49322a842)

**Comment by csbhr** [comment]
FFHQ-UV数据集中的头发都是一致的，但训练好的StyleGAN2生成的头发的方向有时会翻转。头发一般不是关注的区域，所以不会有什么影响。
