### ISSUE TITLE
Add eyeball into head mesh

### ISSUE THREAD

**Issue by Bitree10086** [csbhr/FFHQ-UV#56]
Hi, @csbhr 
Thank you for your excellent work！I want to add eyeballs to the file generated in this RGB fitting, but through sh run_ mesh_ add_ Eyeball.sh, there seems to be no change. How do I add eyeballs to the generated files during the RGB fitting stage?

**Comment by ImistroI** [comment]
Hi I am also interested, do u got any solution? :)
