### ISSUE TITLE
The reconstruction model training by myself is so weird

### ISSUE THREAD

**Issue by xingpeima** [csbhr/FFHQ-UV#7]
I tried to train a face reconstruction model on the basis of hifi3d++ based on [Deep3DFaceRecon_pytorch](https://github.com/sicxu/Deep3DFaceRecon_pytorch), but serious deformation appeared around the mouth and eyes, and it seems that the effect of training is not enough, do you have encountered such a problem, do you have any good solutions?
![image](https://user-images.githubusercontent.com/63437590/208804216-76fe7001-ef10-4ac0-81f5-7f9e8af08bb6.png)

**Comment by csbhr** [comment]
In the training process, we propose to restrict the coefficients of expression basis to be non-negative, that is, to use the ReLU activation function before outputting the coefficients of the expression basis. This might solve the problem.

You can refer to [the source code](https://github.com/csbhr/FFHQ-UV/blob/main/RGB_Fitting/network/recon_deep3d.py#L36).
