### ISSUE TITLE
the correspondence of FFHQ

### ISSUE THREAD

**Issue by qiuyuda** [csbhr/FFHQ-UV#8]
Thanks for the great work.
According to the paper, the released dataset has been filtered. 

Is there any metohd to get the correspondence of the dataset with FFHQ?

**Comment by csbhr** [comment]
Recently I am occupied by other things, in the near future, we will provide project details of the FFHQ-UV dataset creation pipeline, including inversion latents/faces, detected face attributes, sample correspondence, etc.

**Comment by csbhr** [comment]
The corresponding indices in original FFHQ dataset are available now, please refer to this [[README]](https://github.com/csbhr/FFHQ-UV/blob/main/README_dataset.md#normalized-face-images-meta-information) for details.

We mainly focus on the quality and illumination properties of the normalized faces, and do not care about the identity fidelity with the faces in the original FFHQ dataset. Therefore, we do not encourage researchers to look for the correspondence between samples in FFHQ-UV and the original FFHQ dataset. To this end, we shuffle the samples in the FFHQ-UV dataset.

In addition, we additionally introduce a very small number of samples (about 1K samples) to alleviate the data biases of FFHQ and StyleGAN (e.g., dark-skinned faces). For these samples, we do not provide indices in the original FFHQ dataset.
